### ISSUE TITLE
Chronicler stopping never finishes.

### ISSUE THREAD

**Issue by MarcoDiMarek** [arciisine/vscode-chronicler#25] opened 2021-05-29 17:24 UTC
FFMPEG is in path (environment variables), slashes in DEST and FFMPEG paths in settings JSON are escaped.
Still, upon running, Chronicler gives an invalid exit status and when stopping, it never actually stops.

**Comment by arciisine** [comment] 2021-05-31 01:45
Do you have a sample config?  Also knowing what platform you are on is helpful as well.

**Comment by MarcoDiMarek** [comment] 2021-05-31 05:40
I was on Windows 10.
Sorry, I uninstalled it since I don't want to keep addons I do not actively use.

**Comment by manuelamr** [comment] 2021-06-16 16:40
Seme problem, but under Fedora Linux 33 (VSCode 1.57.0)
![image](https://user-images.githubusercontent.com/68553883/122258841-ceec2000-ced1-11eb-8e65-69eea9c81d9b.png)

After click on "Chronicler start" button bar, inmediately shows above error.
I enabled debug log too, but i didn't find the log file, or log window extension

FFMpeg v4.3.2 installed and binary locate at /usr/bin/ffmpeg

**Comment by arciisine** [comment] 2021-06-20 16:47
@manuelamr I think this is a different issue.  Do you know if you happen to be running Wayland?  Currently Wayland doesn't play well with screen recording by process id.

**Comment by manuelamr** [comment] 2021-06-21 11:01
> @manuelamr I think this is a different issue. Do you know if you happen to be running Wayland? Currently Wayland doesn't play well with screen recording by process id.

It's not wayland.
Current problems are on XOrg

**Comment by arciisine** [comment] 2021-06-21 12:15
Thanks @manuelamr. The vscode plugin relies on @arcsine/win-info and @arcsine/screen-recorder as bulk of the functionality.  To debug,  can you try running `npx @arcsine/win-info` and share the output..  This will help to determine if there is any issue with detecting screens, dimensions, etc.

Also, if you can run `npx @arcsine/screen-recorder test.mp4`, and share that output as well . This will help to determine if there are any issues with ffmpeg and recording at all.

**Comment by manuelamr** [comment] 2021-06-21 14:17
> Thanks @manuelamr. The vscode plugin relies on @arcsine/win-info and @arcsine/screen-recorder as bulk of the functionality. To debug, can you try running `npx @arcsine/win-info` and share the output.. This will help to determine if there is any issue with detecting screens, dimensions, etc.
> 
> Also, if you can run `npx @arcsine/screen-recorder test.mp4`, and share that output as well . This will help to determine if there are any issues with ffmpeg and recording at all.

Attached debug log file @arciisine 
[screen-recorder.log](https://github.com/arciisine/vscode-chronicler/files/6687218/screen-recorder.log)

**Comment by arciisine** [comment] 2021-06-21 15:00
Thanks @manuelamr, the ffmpeg output points to:

```
[x11grab @ 0x55f11fdff900] Cannot open display :0.0+0,32, error 1.
:0.0+0,32: Input/output error
Invalid exit status: 1
```

So it looks like there is some issue with the display naming.  Are you able to run the `npx @arcsine/win-info` command.  That should give some additional clarity.

**Comment by manuelamr** [comment] 2021-06-21 15:02
Attached win-info.log @arciisine 

[win-info.log](https://github.com/arciisine/vscode-chronicler/files/6687598/win-info.log)

**Comment by arciisine** [comment] 2021-06-21 16:46
Thanks again for bearing with me.  These types of issues can be hard to track down. I'm wondering if it is the :0.0 vs just :0, can you run `echo $DISPLAY` to show what your display number is.

**Comment by manuelamr** [comment] 2021-06-21 17:13
echo $DISPLAY
:1

**Comment by arciisine** [comment] 2021-06-21 17:47
Okay, so that is definitely the issue, as the code is trying to run at :0.0 for some reason. I need to dig into this a little more, as I need to ensure that the display number is honored.

**Comment by arciisine** [comment] 2021-06-21 17:50
@manuelamr I just pushed another version of `@arcsine/screen-recorder`.  If you could retry that operation from before 
`npx @arcsine/screen-recorder test.mp4`, this should hopefully work now.

**Comment by manuelamr** [comment] 2021-06-21 17:55
yes!! now its working
I've uploaded a mediainfo log from the test file generated.

[test.mp4.mediainfo.log](https://github.com/arciisine/vscode-chronicler/files/6688571/test.mp4.mediainfo.log)
[screen-recorder-2.log](https://github.com/arciisine/vscode-chronicler/files/6688565/screen-recorder-2.log)

**Comment by arciisine** [comment] 2021-06-21 18:02
Awesome.  Extension should release under 0.1.12.  Please let me know if the issue isn't resolved.

**Comment by manuelamr** [comment] 2021-06-23 09:27
Excellent! with v0.1.12, works like a charm!!
Good job @arciisine 

https://user-images.githubusercontent.com/68553883/123072531-ed907080-d415-11eb-9be1-c1285b04e6af.mp4

**Comment by arciisine** [comment] 2021-06-24 17:40
Closing the issue then.

**Closed as completed by arciisine** 2021-06-24 17:40 UTC

**Comment by niuyuping** [comment] 2022-07-17 02:41
I am working on the version 0.1.16 and also get this problem, the log is below:

npx @arcsine/screen-recorder test.mp4

npx: installed 6 in 8.013s
/usr/bin/ffmpeg -threads 4 -video_size 1920x1048 -f x11grab -i :0.0+0,32 -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  test.mp4
Recording for 5 seconds...
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-libsmbclient --enable-version3 --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzvbi --enable-lv2 --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[x11grab @ 0x55f11fdff900] Cannot open display :0.0+0,32, error 1.
:0.0+0,32: Input/output error
Invalid exit status: 1
(node:100717) UnhandledPromiseRejectionWarning: Error: Invalid exit status: 1
    at ChildProcess.<anonymous> (/home/manuelamr/.npm/_npx/100717/lib/node_modules/@arcsine/screen-recorder/lib/util.js:32:28)
    at Object.onceWrapper (events.js:483:26)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:100717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:100717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done

**Comment by arciisine** [comment] 2022-07-17 22:59
It looks like there could be an issue with the $DISPLAY variable,

[x11grab @ 0x55f11fdff900] Cannot open display :0.0+0,32, error 1.

Can you run 'echo $DISPLAY' and also share what window manager/desktop
environment you are using?

**Comment by niuyuping** [comment] 2022-07-18 08:15
I tried to run 'echo $DISPLAY' in console but nothing......I am using an iMac Pro 2018 with a DELL U2720QM external display
![image](https://user-images.githubusercontent.com/24621930/179470254-657e2eb8-f3a3-409c-b7a7-5aa4b546f5b3.png)
![image](https://user-images.githubusercontent.com/24621930/179470323-bde4d6b3-8530-4a7a-b1fc-cfaace93b0de.png)

I ran 'npx @arcsine/screen-recorder test.mp4' for a test, the output is below:
/usr/local/bin/ffmpeg -f avfoundation -list_devices true -i ""
Invalid exit status: 1
/usr/local/bin/ffmpeg -capture_cursor 1 -threads 4 -f avfoundation -i 1:none -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  -vf 'scale=2560:1440:flags=lanczos,crop=2559:1314:1:25' test.mp4
Recording for 5 seconds...
ffmpeg version 4.4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
objc[26265]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
objc[26265]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
[AVFoundation indev @ 0x7fcb01712f80] Configuration of video device failed, falling back to default.
[avfoundation @ 0x7fcb01809a00] Selected pixel format (yuv420p) is not supported by the input device.
[avfoundation @ 0x7fcb01809a00] Supported pixel formats:
[avfoundation @ 0x7fcb01809a00]   uyvy422
[avfoundation @ 0x7fcb01809a00]   yuyv422
[avfoundation @ 0x7fcb01809a00]   nv12
[avfoundation @ 0x7fcb01809a00]   0rgb
[avfoundation @ 0x7fcb01809a00]
bgr0
[avfoundation @ 0x7fcb01809a00] Overriding selected pixel format to use uyvy422 instead.
Done

**Comment by sugatoray** [comment] 2022-12-19 20:40
Same for me. `Chronicler stopping...` never stops.

- System: `macOS Ventura 13.0.1`

I checked the `$DISPLAY` variable as well. It is empty.

```sh
echo $DISPLAY
```

So ran `npx @arcsine/screen-recorder test.mp4` for diagnostics.

<details>
<summary>Click to see Results</summary>
<p>

```sh
Need to install the following packages:
  @arcsine/screen-recorder@0.2.9
Ok to proceed? (y) y
/opt/homebrew/bin/ffmpeg -f avfoundation -list_devices true -i ""
Invalid exit status: 1
/opt/homebrew/bin/ffmpeg -capture_cursor 1 -threads 4 -f avfoundation -i 1:none -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  -vf 'scale=1512:982:flags=lanczos,crop=1512:945:0:37' test.mp4
Recording for 5 seconds...
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
objc[47362]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
objc[47362]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
objc[47362]: class `NSKVONotifying_AVCaptureScreenInput' not linked into application
[AVFoundation indev @ 0x14a711e70] Configuration of video device failed, falling back to default.
[avfoundation @ 0x14a711ac0] Selected pixel format (yuv420p) is not supported by the input device.
[avfoundation @ 0x14a711ac0] Supported pixel formats:
[avfoundation @ 0x14a711ac0]   uyvy422
[avfoundation @ 0x14a711ac0]   yuyv422
[avfoundation @ 0x14a711ac0]   nv12
[avfoundation @ 0x14a711ac0]   0rgb
[avfoundation @ 0x14a711ac0]   bgr0
[avfoundation @ 0x14a711ac0] Overriding selected pixel format to use uyvy422 instead.
Done
```

</p>
</details>

**Comment by arciisine** [comment] 2022-12-19 20:47
Try uninstalling ffmpeg from homebrew, and letting the extension install itself.  Realistically it shouldn't matter, but most likely some config differences.

**Comment by sugatoray** [comment] 2022-12-19 20:53
@arciisine Chronicler is not offering to install ffmpeg (even though I have uninstalled ffmpeg from my system and reloaded the VS Code window).

**Comment by arciisine** [comment] 2022-12-19 20:55
You most likely need to clear out the ffmpeg location value from within the settings and reload the editor.  It will not prompt the download if ffmpeg looks to already be installed.

**Comment by sugatoray** [comment] 2022-12-19 21:07
Did what you suggested. Chronicler installed ffmpeg. But now after I start recording, it once again shows the same problem: indefinite `Chronicler stopping...` status.

**Comment by sugatoray** [comment] 2022-12-19 21:16
And now I am getting this error.

```sh
$ npx @arcsine/screen-recorder test.mp4
/Users/sugatoray/.npm/_npx/c71e018737289961/node_modules/@arcsine/screen-recorder/lib/os.js:21
        throw new Error(`Cannot find ${name} on path`);
              ^

Error: Cannot find ffmpeg on path
    at OSUtil.findFileOnPath (/Users/sugatoray/.npm/_npx/c71e018737289961/node_modules/@arcsine/screen-recorder/lib/os.js:21:15)
    at async FFmpegUtil.findFFmpegBinIfMissing (/Users/sugatoray/.npm/_npx/c71e018737289961/node_modules/@arcsine/screen-recorder/lib/ffmpeg.js:105:34)
    at async run (/Users/sugatoray/.npm/_npx/c71e018737289961/node_modules/@arcsine/screen-recorder/lib/cli.js:13:18)

Node.js v19.1.0
```

> location where Chronicler installed/downloaded ffmpeg is: `$HOME` (`/home/sugatoray`)
